husainali72/Ravendel-Next.js-Node.js-GraphQL-Based-Headless-eCommerce-Web-Application

gqschema/blog.js
resolvers/blog.js
server.js

blog and blog tag  message and status code implemented

blog and blog tag message status

---

gqschema/page.js
resolvers/blog.js
resolvers/page.js

pagemessage

---

config/helpers.js
error.js
gqschema/Review.js
gqschema/blog.js
gqschema/brand.js
gqschema/coupon.js
gqschema/customer.js
gqschema/index.js
gqschema/mics.js
gqschema/page.js
gqschema/product.js
gqschema/product_attribute.js
gqschema/user.js
resolvers/blog.js
resolvers/brand.js
resolvers/coupon.js
resolvers/customer.js
resolvers/page.js
resolvers/product.js
resolvers/product_attribute.js
resolvers/review.js
resolvers/user.js
validations/blog.js

status code

---

client/src/views/reviews/editreview.js
config/api_functions.js
config/keys.js
config/messages.js
gqschema/cart.js
package.json
resolvers/cart.js
resolvers/review.js

- removed unnecessary console logs
- reassign live mongodb database
- code fixes in various files

major bug fixes

---

config/api_functions.js
config/messages.js
gqschema/customer.js
models/Customer.js
resolvers/customer.js

added customer gender
added customer password update

customer update

---

client/src/queries/orderQuery.js
client/src/queries/settingQuery.js
frontend/src/queries/productQuery.js
frontend/src/views/singleproduct/index.js
frontend/src/views/singleproduct/productotherdetail.js
gqschema/order.js
gqschema/setting.js
models/Order.js
models/Setting.js
resolvers/order.js
resolvers/setting.js
routes/api/customers.js

Order update

---

gqschema/cart.js
resolvers/cart.js

Added changeQty API
Changed working of addCart API

cart-changes

---

resolvers/cart.js

- changed approach on addCart API

RD-17 changed approach on addCart API

---

config/helpers.js
gqschema/misc.js
models/Setting.js
resolvers/user.js

- Implemneted orderChart API
- Updated add_section_web and mobile_section to empty array

RD-20 orderChart API

---

config/helpers.js
config/messages.js
models/User.js
resolvers/blog.js
resolvers/user.js

- Implemented delete file from local if upload on AWS
- Some changes in blog API

RD-21 remove photo after AWS upload

---

client/src/views/coupon/addCoupon.js
client/src/views/coupon/editCoupon.js
config/api_functions.js
config/helpers.js
gqschema/setting.js
resolvers/blog.js
resolvers/brand.js
resolvers/coupon.js
resolvers/customer.js
resolvers/faq.js
resolvers/page.js
resolvers/product.js
resolvers/product_attribute.js
resolvers/review.js
resolvers/setting.js
resolvers/shipping.js
resolvers/tax.js
resolvers/user.js

- Resolved slider images issue from backend in updateAppearanceHome API
- Resolved image deletion issue in updateUser API
- Resolved review not updating
- Verified add product and update product changes not being display in frontend
- Resolved duplication error in necessary APIs
- Resolved coupon datatype errors

BE-bug-fixes

---

resolvers/product.js

- Added brand values in edit product API

RD-24 Fixed API Issues

---

frontend/components/Header.js
frontend/components/category/onSaleProductCard.js
frontend/lib/getStripe.js
frontend/package.json
frontend/pages/api/stripe.js
frontend/pages/categorys/[categorys].js
frontend/pages/index.js
frontend/pages/shopcart.js

fixed some problems when deleting and clearing cart items

RD-23 some fixes in cart

---

gqschema/product.js
resolvers/product.js

- Changed approach on filteredProducts API

RD-29 Filtered Products

---

config/api_functions.js
config/helpers.js
gqschema/product.js
models/Product.js
package.json
resolvers/order.js
resolvers/review.js
server.js

- Product Avg Rating based on review ratings
- removed unnecessary console log
- removed nodemon from package.json
- cron schedulers in server.js

RD-41 Product Avg Rating

---

config/api_functions.js
config/helpers.js

- Fixed issue in email
- Fixed issue of last modified date

Backend Fixes

---

config/aws.js
config/helpers.js
gqschema/blog.js
gqschema/brand.js
gqschema/product.js
gqschema/setting.js
gqschema/user.js
models/Blog.js
models/Brand.js
models/Product.js
models/ProductAttributeVariation.js
models/ProductCat.js
models/User.js
resolvers/blog.js
resolvers/brand.js
resolvers/product.js
resolvers/setting.js
resolvers/tax.js
resolvers/user.js

- Changed image configuration for simplicity
- Proper naming for tax errors

RD-50 Change Image Configuration

---

config/api_functions.js
config/messages.js
resolvers/product.js
resolvers/shipping.js
resolvers/tax.js

- RD-36 fixed issue of percentage
- Fixed filtered products issue and added rating as well
- Added check for customer_id and product_id

Backend Bug Fixes

---

frontend/components/cardcomponent/CardDetail.js
frontend/components/category/GalleryImage.js
frontend/components/category/onSaleProductCard.js
frontend/pages/index.js
frontend/pages/product/[singleproduct].js
frontend/pages/shop.js
frontend/pages/shopcart.js
frontend/redux/reducers/cart.js
frontend/styles/globals.css
frontend/utills/helpers.js

- fixed currency in all the required places 
- shop cart price fix
- fix homepage UI
- fixed recent product issue
- fixed some minor issues in shop cart page

Currency changes

---

frontend/components/account/login.js
frontend/components/category/category.js
frontend/pages/blogs/[blogs].js
frontend/pages/category/[categorys].js
frontend/pages/subcategory/[category].js
frontend/redux/reducers/cart.js
frontend/styles/globals.css

This commit contains following updates:
- clear cart on login after cart merged
- correct paths spelling
- changed category and sub category page

Build Error Fix

---

client/src/App.js
client/src/queries/settingQuery.js
client/src/views/components/validate.js
client/src/views/settings/components/themes.js
gqschema/setting.js
models/Setting.js
resolvers/setting.js

Added 4 new fields in settings theme:
- playstore url
- appstore url
- email
- phone number

RD-52 Added fields in settings theme

---

frontend/components/account/component/OrderDetailAfter.js
frontend/components/account/login.js
frontend/components/cardcomponent/LoadingCard.js
frontend/components/checkoutcomponent/CheckOutOrderSummary.js
frontend/components/checkoutcomponent/CustomerDetails.js
frontend/components/checkoutcomponent/OrderDetail.js
frontend/components/shoppage/shopProducts.js
frontend/package.json
frontend/pages/category/[categorys].js
frontend/pages/checkout.js
frontend/pages/orderstatus/thankyou.js
frontend/pages/shopcart.js
frontend/queries/couponquery.js
frontend/queries/orderquery.js
frontend/styles/globals.css

This commit contains changes  and fixes of checkout page and thankyou page 
- skeleton loader for cart page
- loader when applying valid coupon and alert messages .

Changes For COD checkout

---

config/helpers.js
gqschema/setting.js
models/Setting.js
resolvers/order.js
resolvers/setting.js

- Changed order number #00001
- Added order options in setting for order number

RD-55 Changed order_number format

---

client/src/queries/couponQuery.js
config/helpers.js
gqschema/coupon.js
models/Coupon.js
resolvers/cart.js
resolvers/coupon.js

- updated calculateCoupon API
- updated calculateCart API

RD-10 updated calculateCoupon API

---

client/src/queries/productQuery.js
client/src/store/action/productAction.js
client/src/utils/helper.js
config/api_functions.js
config/helpers.js
gqschema/product.js
gqschema/setting.js
resolvers/cart.js
resolvers/product.js
resolvers/setting.js

- order_number code optimization
- added check for published products
- handled product variants code
- added param for display published/allproducts in admin/frontend

RD-57 Backend Issues

---

frontend/components/Footer.js
frontend/components/account/component/OrderDetailAfter.js
frontend/components/banner/homebanner.js
frontend/components/category/GalleryImage.js
frontend/components/category/category.js
frontend/components/category/onSaleProductCard.js
frontend/components/category/productNavbar.js
frontend/components/category/pruductcart.js
frontend/components/shoppage/shopProducts.js
frontend/pages/brands/[brand].js
frontend/pages/category/[categorys].js
frontend/pages/checkout.js
frontend/pages/index.js
frontend/pages/orderstatus/thankyou.js
frontend/pages/product/[singleproduct].js
frontend/pages/shopcart.js
frontend/pages/subcategory/[category].js
frontend/queries/orderquery.js
frontend/styles/globals.css
frontend/utills/helpers.js

- Address in footer is now coming from client side
- Coupon code query change
- Order Detail page changed,  now showing coupon details and correct grand total
- Pricing and discount issues fixed everywhere it is  used
- Right side categories on category page will only show its products instead of showing its subcategories on clicking
- Meta title, description and keyword added correctly everywhere

RD-70 by Shridhar

---

client/src/queries/settingQuery.js
gqschema/setting.js
models/Setting.js
resolvers/blog.js
resolvers/brand.js
resolvers/coupon.js
resolvers/faq.js
resolvers/page.js
resolvers/product.js
resolvers/product_attribute.js
resolvers/review.js
resolvers/setting.js

- Added notification in settings
- Added social media in appearance > theme
- Added appropriate text to error statements
- Added frontend query for order options, notification, social media

RD-58 Backend updated settings

---

models/Setting.js
resolvers/brand.js

- Added appropriate msg in brand when duplicate brands added
- Added deafult icons in setting > social_media

BE-fixes brand, socialMedia

---

gqschema/setting.js
models/Setting.js
resolvers/setting.js

- Added Slider in Settings > mobile

RD-60-BE added slider in mobile

---

frontend/components/Footer.js
frontend/components/SpecificProducts.js
frontend/components/category/GalleryImage.js
frontend/components/category/category.js
frontend/components/category/featurebrand.js
frontend/components/category/onSaleProductCard.js
frontend/components/category/productNavbar.js
frontend/components/category/pruductcart.js
frontend/components/checkoutcomponent/OrderDetail.js
frontend/components/shoppage/shopProducts.js
frontend/pages/blog.js
frontend/pages/checkout.js
frontend/pages/contact.js
frontend/pages/product/[singleproduct].js
frontend/pages/shop.js
frontend/pages/subcategory/[category].js
frontend/queries/home.js
frontend/styles/globals.css
frontend/utills/calculateDiscount.js

- Added address and contacts details coming from backend
- Added margins between home page sections
- Remove round off where discount % are shown, now its actual discount will show up to two decimal places
- In order detail component in checkout page where products are shown they were non clickable so added Links to redirect them to that specific product page
- In category component added accurate back functionality on parent heading categories
- Fix blog page UI when more blogs are there it was overflowing and some data goes hidden
- Added address and contact details on contact page coming from backend
- Fix html parser in product description
- calculate discount function changed

RD-75 by Shridhar

---

client/src/queries/settingQuery.js
client/src/views/settings/components/inventory.js
client/src/views/settings/components/storeAddress.js
config/helpers.js
gqschema/index.js
gqschema/setting.js
gqschema/zipcode.js
models/Setting.js
models/Zipcode.js
resolvers/index.js
resolvers/product.js
resolvers/setting.js
resolvers/zipcode.js

- Implemented code for zipcode check for products
- Added new hour field of store in settings > store> store address

RD-59-BE Implemented zipcode code

---

config/helpers.js
gqschema/order.js
models/Cart.js
models/Order.js
resolvers/blog.js
resolvers/brand.js
resolvers/cart.js
resolvers/customer.js
resolvers/faq.js
resolvers/order.js
resolvers/page.js
resolvers/product.js
resolvers/product_attribute.js
resolvers/review.js
resolvers/user.js
resolvers/zipcode.js

- Corrected calculateCoupon messages
- Added proper validation to necessary fields
- Changed subtotal details in order to display total of all products collectively
- Added check for case sensitivity when checking for duplicate data 
- Modified subtotal details in order to calculate shipping and tax based on product
- Added shipping_class and tax_class field in cart model for above reason
- Added duplication check in review based on customer and product

BE bug fixes

---

config/helpers.js
gqschema/cart.js
models/Cart.js
package.json
resolvers/cart.js

1-- Remove required in cart models 
2 --inside cart resolvers I made changes in addcart by only save product id ,varient id and quantity

New branch 07 11 2023

---

config/helpers.js
package.json
resolvers/cart.js
routes/api/razorpay.js
server.js

verify razorpay payment

---

config/helpers.js

Made changes in the amount break down of Paypal request to resolve the issue

Bug Fixed in the add order if payment mode is Paypal

---

client/src/views/product/editProduct.js

…en 'Do you want to track inventory?' is disabled

ADD/Edit product - Implemented condition to remove quantity field  when 'Do you want to track inventory?' is disabled

---

client/src/queries/groupProductQuery.js
client/src/views/product/addGroup.js
config/api_functions.js
gqschema/productGroup.js
models/ProductGroup.js
resolvers/productGroup.js
resolvers/product_attribute.js

- Added Validation in Admin > Product > Attribute (Special Character Validation)
- Added Status field in Group Product(Add, edit, Get)
- Added Date Sort in Product Group
- Made required FE changes for working of the status field

Added status in product group and other fixes

---

resolvers/product.js

Fixed following tickets
- https://app.asana.com/0/1206326550962233/1207478458144561
- https://app.asana.com/0/1206307414740952/1207478458144555

Fixed getCategoryPageData API issues
